### ISSUE TITLE
Instead of .findAll().first(); you can use findFirst()

### ISSUE THREAD

**Issue by ordago** [rakuishi/todo-android#3]
https://github.com/rakuishi/todo-android/blob/master/app/src/main/java/com/rakuishi/todo/persistence/TodoRealmManager.java#L20

https://realm.io/docs/java/latest/api/io/realm/RealmQuery.html#findFirst--

**Comment by rakuishi** [comment]
Thank you.
I should use `findFirst()` instead of `findAll().fist()`.
